### ISSUE TITLE
ALLOWED_HOST not loading correct value

### ISSUE THREAD

**Issue by bglopez** [RyanNoelk/OpenEats#248]
Edit: So I have found this to be related to ALLOWED_HOST but even with a setting of "*" the issue still persists. I'll take a dig at this since I've just gotten home from work.

I am seeing an issue using the production docker-compose and env files (suited for my environment and verified working otherwise, explained later in post) -- if I bring up the containers with "DJANGO_DEBUG=False" I will always receive a 400 - Bad Request error when attempting to access the API. If I set this to "True" then everything functions as expected. I haven't been able to figure out why just yet, but there isn't anything special about my setup that differs from the documentation examples. I can provide any information needed to help debug since I don't think running with Django debug on is a great idea.

My compose file and env is a bit different but I've tried this with the defaults and saw the same problem occurring so I don't believe they are related.

env_prod.list
```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=root

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
# openssl rand -hex 32
DJANGO_SECRET_KEY=blahblahblahblahblah
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=True
ALLOWED_HOST='food.neverlocate.me'
HTTP_X_FORWARDED_PROTO=True

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_PORT=8080
NODE_API_URL=https://food.neverlocate.me
NODE_LOCALE=en
```

docker-compose.yml
```
version: '2'
services:
  api:
    build: api/
    command: ./base/gunicorn_start.sh
    restart: on-failure
    volumes:
      - /opt/openeats/static-files:/code/static-files
      - /opt/openeats/site-media:/code/site-media
    depends_on:
      - db
    ports:
      - "8007:8000"
    env_file:
      env_prod.list
  node:
    build: frontend/
    command: npm start
    volumes:
      - node_modules:/code/node_modules
    depends_on:
      - api
    ports:
      - "8008:8080"
    env_file:
      env_prod.list
  db:
    image: mariadb
    volumes:
      - /opt/openeats/db:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    env_file:
      env_prod.list
volumes:
  node_modules:
```

nginx (food.conf)
```
upstream api {
  ip_hash;
  server 127.0.0.1:8007;
}

upstream node {
  ip_hash;
  server 127.0.0.1:8008;
}

server {
    listen 443 http2;
    server_name food.neverlocate.me;
    ssl on;
    ssl_certificate /etc/nginx/certs/food-fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/food-key.pem;
    ssl_dhparam /etc/nginx/certs/dhparam.pem;
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_pass http://node/;
    }

    location /api/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_pass http://api;
    }

    location /admin/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_pass http://api;
    }

    location /static-files/ {
        root /opt/openeats;
        try_files $uri /static-files/$uri;
    }

    location /site-media/ {
        root /opt/openeats;
        try_files $uri /site-media/$uri;
    }
}
server {
    listen 80 ;
    server_name food.neverlocate.me;

    return 301 https://food.neverlocate.me$request_uri;
}
```

**Comment by bglopez** [comment]
So I've managed to fix this, at least temporarily, by manually adding my host in ALLOWED_HOSTS in api/base/settings.py -- it seems like the environment variable is not getting passed along and properly processed by the api container.

**Comment by RyanNoelk** [comment]
Have you tried removing the quotes around your ALLOWED_HOST env var?
Change `ALLOWED_HOST='food.neverlocate.me'` -> `ALLOWED_HOST=food.neverlocate.me`

**Comment by bglopez** [comment]
Hi Ryan,

I just gave that a try with the same results. I'm just putting together a BASH script quickly to take care of taking in the domain, generating a secret and pushing out the changes to Dockerfiles, etc then running docker-compose automatically. It should help with getting it deployed a bit easier for people and I want to tackle this problem a bit myself since it's interesting. I'll post it in this issue when I've finished.

**Comment by bglopez** [comment]
This is kind of hacky, but it works for me. Definitely has room for improvement though: 

prod-build.sh
```
#!/bin/bash
set -euo pipefail

allowedhost() {
    echo "Which host/domain name will this be accessed by?"
    read -r -s varAllowedHost
    if [[ -z varAllowedHost ]]; then
        echo "Nothing provided as input. Stopping."
        exit 1
    else
        echo "Using domain: ${varAllowedHost}"
    fi
}

djangosecret() {
    echo "Generating Django secret..."
    varDjangoSecretKey=`openssl rand -hex 32`
    if [[ -z $varDjangoSecretKey ]]; then
        echo "Django secret failed to generate."
        echo "Missing openssl (or really old?) Exiting."
        exit 1
    fi
}

djangosettings() {
    defaultdjangodebug='false'
    defaultdjangohttpxforwarded='true'
    echo "Django Settings"
    echo "Enable Django debug mode (true/false)? Defaults to false."
    read -e -i "$defaultdjangodebug" inputdebug
    echo "Enable HTTP X_FORWARDED_PROTO (true/false)?"
    varDjangoDebug=${inputdebug:-$defaultdjangodebug}
    echo "If you're using nginx, Apache or some other forward proxy with HTTPS, set to true. Defaults to true."
    read -e -i "$defaultdjangohttpxforwarded" inputforward
    varDjangoHttpForwarded=${inputforward:-$defaultdjangohttpxforwarded}
    if [[ -z $varDjangoDebug ]] || [[ -z $varDjangoHttpForwarded ]]; then
        echo "Something was not set. Please try again. Exiting."
        exit 1
    fi
}

nodesettings() {
    defaultapiurl=localhost:8080
    defaultnodelocale=en
    echo "Change Node API URL? Defaults to localhost:8080 (recommended)"
    read -e -i "$defaultapiurl" inputapi
    varNodeAPIURL=${inputapi:-$defaultapiurl}
    echo "Change Node locale? Defaults to en (recommended)"
    read -e -i "$defaultnodelocale" inputlocale
    varNodeLocale=${inputlocal:-$defaultnodelocale}
}

mysqlsettings () {
    defaultmysqlroot=`openssl rand -hex 16`
    defaultmysqldb=openeats
    echo "Set MySQL root password? Defaults to a randomly generated 16 character password."
    read -e -i "$defaultmysqlroot" inputroot
    varMySQLrootpassword=${inputroot:-$defaultmysqlroot}
    echo "Change MySQL database name? Defaults to openeats"
    read -e -i "$defaultmysqldb" inputdb
    varMySQLDB=${inputdb:-$defaultmysqldb}
}

dockersed() {
    for var in ${!var@}; do
        sed -i "s/$var/${!var}/" docker-prod-template.yml
    done
}

main() {
   echo "OpenEats quick setup script"
   echo "Running domain setup ..."
   allowedhost
   echo "Generating Django secret"
   djangosecret
   echo "Running Django settings setup ..."
   djangosettings
   echo "Running Node settings setup ..."
   nodesettings
   echo "Running MySQL settings setup ..."
   mysqlsettings
   echo "Generating finished docker-compose production file"
   dockersed
}

main
```

docker-prod-template.yml
```
version: '2'
services:
  api:
    image: openeats/api
    command: ./base/gunicorn_start.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    environment:
      - ALLOWED_HOST=varAllowedHost
      - API_URL=0.0.0.0:8000
      - API_PORT=8000
      - DJANGO_SECRET_KEY=varDjangoSecretKey
      - DJANGO_DEBUG=varDjangoDebug
      - HTTP_X_FORWARDED_PROTO=varDjangoHttpForwarded
  node:
    image: openeats/node
    command: npm start
    volumes:
      - node_modules:/code/node_modules
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - NODE_URL=localhost:8080
      - NODE_PORT=8080
      - NODE_API_URL=varNodeAPIURL
      - NODE_LOCALE=varNodeLocale
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=varMySQLDB
      - MYSQL_ROOT_PASSWORD=varMySQLrootpassword
  nginx:
    image: openeats/nginx
    command: ./start.sh
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
volumes:
  database:
  node_modules:
  static-files:
  site-media:
```

After running the script and then doing ```docker compose -f docker-prod-template.yml up -d``` I was able to verify that everything works.

```
[root@neverlocate OpenEats]# curl -vvvv -H 'Host: food.neverlocate.me' http://127.0.0.1:86/api/v1
* About to connect() to 127.0.0.1 port 86 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 86 (#0)
> GET /api/v1 HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: food.neverlocate.me
>
< HTTP/1.1 404 Not Found
< Server: nginx/1.13.3
< Date: Tue, 29 Aug 2017 00:29:16 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Language, Cookie
< Content-Language: en
<
* Connection #0 to host 127.0.0.1 left intact
```
