### ISSUE TITLE
[docker-prod] login not possible

### ISSUE THREAD

**Issue by jhartlep** [RyanNoelk/OpenEats#279]
Hi,
I wanted an openeats (prod) instance on my vserver.

So I created the two files docker-compose.yml and env_prod.list and called
`docker-compose up -d` and the first time setup. After this, I created a new nginx reverse proxy configuration on my host system (for https).

The site is displayed correctly in my browser, but I cannot log in with the superuser created in the first time setup. I just get an error "Unable to login!","Please confirm that the username and password are correct."

Below I quoted my configs (docker-compose.yml, env_prod.list and my nginx reverse config for this subdomain).
Can somebody help finding the error?

Thanks,
Jens

**docker-compose.yml**
```yml
version: '2'
services:
  api:
    image: openeats/api
    container_name: openeats_api
    command: ./base/gunicorn_start.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    env_file:
      env_prod.list
  node:
    image: openeats/node
    container_name: openeats_node
    command: npm start
    volumes:
      - node_modules:/code/node_modules
    depends_on:
      - api
    env_file:
      env_prod.list
  db:
    image: mariadb
    container_name: openeats_db
    env_file:
      env_prod.list
  nginx:
    image: openeats/nginx
    container_name: openeats_nginx
    command: ./start.sh
    ports:
      - "8092:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    env_file:
      env_prod.list
volumes:
  database:
  node_modules:
  static-files:
  site-media:
```

**env_prod.list**
```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=<root-pw>

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=<secret-key>
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST='openeats.domain.de'

# If you are serving content behind an HTTPS proxy,
# Set this to `true`.
# See: https://docs.djangoproject.com/en/1.10/ref/settings/#secure-proxy-ssl-header
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_PORT=8080
NODE_API_URL=https://openeats.domain.de
NODE_LOCALE=de
```

**nginx reverse server config**
```nginx
server {
        listen                          443 ssl http2;
        listen                          [::]:443 ssl http2;
        server_name                     openeats.domain.de;
        server_tokens                   off;

        include                         conf.d/letsencrypt-auth.conf;
        include                         conf.d/ssl.domain.de.conf;

        client_max_body_size            150m;

        charset                         utf-8;

        location / {
                proxy_pass              http://127.0.0.1:8092;
                proxy_set_header        Host                    $host;
                proxy_set_header        X-Real-IP               $remote_addr;
                proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Host        $server_name;
                proxy_connect_timeout   6000;
                proxy_send_timeout      6000;
                proxy_read_timeout      6000;
                send_timeout            6000;
        }
}
```
