### ISSUE TITLE
[Docker] node.js cannot access API

### ISSUE THREAD

**Issue by fmakowski** [RyanNoelk/OpenEats#303]
Hey,

after few attempts to get it up and running, I have finally decided to ask for your help concerning OpenEats production setup with Docker. 

I followed [Running the App guide](https://github.com/RyanNoelk/OpenEats/blob/master/docs/Running_the_App.md). I am using docker-compose with following docker-prod.yml file:

```
version: '2'
services:
  api:
    image: openeats/api
    command: /startup/prod-entrypoint.sh
    restart: unless-stopped
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    env_file:
      env_prod.list
  node:
    image: openeats/node
    command: npm start
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      env_prod.list
    
  db:
    image: mariadb
    env_file:
      env_prod.list
  nginx:
    image: openeats/nginx
    command: ./start.sh
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    env_file:
      env_prod.list
volumes:
  database:
  static-files:
  site-media:
```

and following env_prod.list:

```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=ROOT_PASS

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=SECRET_KEY
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=localhost
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_PORT=8080
NODE_API_URL=http://localhost
NODE_LOCALE=en
```
I fire up `docker-compose -f docker-prod.yml up -d` and the containers are properly created. The app is available under http://localhost:8089, but with no data. For that reason, I type `docker exec -ti xyz_api_1 bash` and use `./manage.py migrate` and `./manage.py createsuperuser` to have at least one account available. Unfortunately, when trying to log in, there is no response from the site - not even an error (so it does not resemble #279 in that matter, where there was an error after trying to log in). I tried to populate database with `./manage.py loaddata ....json` using all available fixtures, but still, nothing happened - also, the data loaded was not shown by the frontend (but it might be that way if the data is available only after logging in...). 

I suspect, that for some reason there is no connection from Node.js to the API - I tried to use `expose: "8000"` for `api` container, but it did not change anything. 

I would be grateful for any help regarding that issue, maybe it's just my mistake in setup or changing of docker-prod.yml file.

Best regards!
Filip
